#! /bin/bash
#
# Usage: pegexp_run_test < pegexp_test_cases
#

while IFS="	" read pegexp text offset result comment
do
	if [ "$pegexp" = '' ]
	then		# Blank line
		echo
	elif [ "${pegexp%%# *}" = '' ]
	then		# Comment line
		echo "$pegexp $text	$offset	$result	$comment"
	else
		./pegexp_test "$pegexp" "$text" |
		(
			IFS="	" read pegexp1 text1 offset1 result1;
			echo "$pegexp1	$text1	$offset1	$result1	$comment"

			if [ "$offset" != "$offset1" -o "$result" != "$result1" ]
			then	echo "Test Failed, got $offset1 $result1 should be $offset $result"
			fi
		)
	fi | expand -t 32,48,56,64 |unexpand -a
done
