#if	!defined(STRPP_MSG_H)
#define	STRPP_MSG_H
/*
 * GENERATED by msggen.cpp from Strpp's own MCS source - do not
 * hand-edit. Regenerate and re-commit after changing it.
 *
 * Strpp's error reporting functions: one per message, gathering the
 * parameters its default text calls for and handing them to the error
 * buffer's Error(). strpp_err.h holds the numbers.
 *
 * Parameters are not typed or named in the MCS schema (a standing
 * decision, and comments aren't part of the parsed tree either), so
 * every parameter here is a plain Variant, named only by position.
 * The hand-written pair this replaced (str_msg.h, until 2026-09-28)
 * used specific types and meaningful names instead. Variant's own
 * non-explicit constructors from StrVal/int/long/long long/const
 * char* make this a drop-in for every call site regardless.
 */
#include	<strpp_err.h>
#include	<errbuf.h>
#include	<strval.h>
#include	<variant.h>

// STR:

inline ErrNum
ErrorSTR_Assert(Variant p1, Variant p2, Variant p3)
{
	return Error(STRERR_ASSERT,
		"At {1}:{2}, assertion failed: `{3}`",
		VariantArray() << p1 << p2 << p3);
}

inline ErrNum
ErrorSTR_TrailingText(Variant p1, Variant p2, Variant p3, Variant p4)
{
	return Error(STRERR_TRAILING_TEXT,
		"The number `{1}` in radix {2} ended at character {3}, leaving `{4}` unread",
		VariantArray() << p1 << p2 << p3 << p4);
}

inline ErrNum
ErrorSTR_NoDigits(Variant p1, Variant p2)
{
	return Error(STRERR_NO_DIGITS,
		"Failed to read a number from `{1}` in radix {2}",
		VariantArray() << p1 << p2);
}

inline ErrNum
ErrorSTR_NumberOverflow(Variant p1, Variant p2, Variant p3, Variant p4)
{
	return Error(STRERR_NUMBER_OVERFLOW,
		"The number `{1}` in radix {2} does not fit in `{3}`, overflowing at character {4}; the value returned is incomplete",
		VariantArray() << p1 << p2 << p3 << p4);
}

inline ErrNum
ErrorSTR_NotNumber(Variant p1, Variant p2, Variant p3, Variant p4)
{
	return Error(STRERR_NOT_NUMBER,
		"Cannot read `{1}` as a number in radix {2}: the character `{3}` at position {4} is not a digit",
		VariantArray() << p1 << p2 << p3 << p4);
}

inline ErrNum
ErrorSTR_NegativeUnsigned(Variant p1, Variant p2)
{
	return Error(STRERR_NEGATIVE_UNSIGNED,
		"Expected `{1}` to be unsigned in radix {2} but it is negative",
		VariantArray() << p1 << p2);
}

inline ErrNum
ErrorSTR_IllegalRadix(Variant p1, Variant p2)
{
	return Error(STRERR_ILLEGAL_RADIX,
		"Attempt to read `{1}` in illegal radix {2} was rejected",
		VariantArray() << p1 << p2);
}

inline ErrNum
ErrorSTR_IndexOutOfRange(Variant p1, Variant p2, Variant p3)
{
	return Error(STRERR_INDEX_OUT_OF_RANGE,
		"Indexing to {1} element {2} in array of {3} elements is not possible",
		VariantArray() << p1 << p2 << p3);
}

// VAR:

inline ErrNum
ErrorVAR_WrongType(Variant p1, Variant p2)
{
	return Error(VARERR_WRONG_TYPE,
		"Expected `{1}`, not `{2}`",
		VariantArray() << p1 << p2);
}

inline ErrNum
ErrorVAR_DoesNotFit(Variant p1, Variant p2)
{
	return Error(VARERR_DOES_NOT_FIT,
		"Value {1} would overflow a `{2}`",
		VariantArray() << p1 << p2);
}

inline ErrNum
ErrorVAR_NoCoercion(Variant p1, Variant p2)
{
	return Error(VARERR_NO_COERCION,
		"Conversion from `{1}` to `{2}` is not implemented, leaving it alone",
		VariantArray() << p1 << p2);
}

// TIM:

inline ErrNum
ErrorTIM_InvalidYMDHMS(Variant p1, Variant p2, Variant p3, Variant p4, Variant p5, Variant p6)
{
	return Error(TIMERR_INVALID_YMDHMS,
		"Date/Time {1}-{2}-{3} {4}:{5}:{6} does not exist",
		VariantArray() << p1 << p2 << p3 << p4 << p5 << p6);
}

inline ErrNum
ErrorTIM_InvalidText(Variant p1)
{
	return Error(TIMERR_INVALID_TEXT,
		"`{1}` is not a valid time, a date or interval",
		VariantArray() << p1);
}

inline ErrNum
ErrorTIM_OutOfRange(Variant p1, Variant p2, Variant p3)
{
	return Error(TIMERR_OUT_OF_RANGE,
		"Date {1} falls outside the range we can hold (from {2} to {3})",
		VariantArray() << p1 << p2 << p3);
}

inline ErrNum
ErrorTIM_NoDate()
{
	return Error(TIMERR_NO_DATE,
		"Wanted a Date but only received a time of day",
		VariantArray());
}

inline ErrNum
ErrorTIM_NoClock()
{
	return Error(TIMERR_NO_CLOCK,
		"No clock is available to provide the current time",
		VariantArray());
}

inline ErrNum
ErrorTIM_NullValue(Variant p1, Variant p2)
{
	return Error(TIMERR_NULL_VALUE,
		"Null value `{1}` received for a {2}",
		VariantArray() << p1 << p2);
}

inline ErrNum
ErrorTIM_ResultOverflow(Variant p1, Variant p2)
{
	return Error(TIMERR_RESULT_OVERFLOW,
		"Result of {1} would overflow a `{2}`",
		VariantArray() << p1 << p2);
}

inline ErrNum
ErrorTIM_NoZone()
{
	return Error(TIMERR_NO_ZONE,
		"You asked for localtime but we don't know the timezone. Using UTC",
		VariantArray());
}

// THR:

inline ErrNum
ErrorTHR_CreateFailed(Variant p1, Variant p2)
{
	return Error(THRERR_CREATE_FAILED,
		"`{1}` returned {2} saying it failed to create a thread",
		VariantArray() << p1 << p2);
}

inline ErrNum
ErrorTHR_StackRefused(Variant p1, Variant p2, Variant p3)
{
	return Error(THRERR_STACK_REFUSED,
		"`{1}` refused a stack size of {2} bytes (error code {3}). Using the default size",
		VariantArray() << p1 << p2 << p3);
}

inline ErrNum
ErrorTHR_JoinFailed(Variant p1, Variant p2)
{
	return Error(THRERR_JOIN_FAILED,
		"Failed to {1} for thread (error code {2}); its exit code is unknown",
		VariantArray() << p1 << p2);
}

inline ErrNum
ErrorTHR_NoCondition(Variant p1)
{
	return Error(THRERR_NO_CONDITION,
		"Cannot {1} condition variable because it was not successfully created",
		VariantArray() << p1);
}

inline ErrNum
ErrorTHR_WaitFailed(Variant p1, Variant p2)
{
	return Error(THRERR_WAIT_FAILED,
		"Thread {1} failed (error code {2})",
		VariantArray() << p1 << p2);
}

inline ErrNum
ErrorTHR_DelayFailed(Variant p1, Variant p2)
{
	return Error(THRERR_DELAY_FAILED,
		"Thread {1} failed (error code {2})",
		VariantArray() << p1 << p2);
}

#endif	// STRPP_MSG_H
