#if	!defined(STRPP_ERR_H)
#define	STRPP_ERR_H
/*
 * GENERATED by msggen.cpp from Strpp's own MCS source - do not
 * hand-edit. Regenerate and re-commit after changing it; see
 * msggen.cpp's own header comment for why the generated file is
 * committed rather than built on demand.
 *
 * Strpp's error numbers: one per message in the set, with the message's
 * default text in a comment. strpp_msg.h holds the function that reports
 * each of these.
 */
#include	<error.h>

#define	STRERR_SET			1	// The message set allocated to the STR
#define	VARERR_SET			2	// The message set allocated to the VAR
#define	TIMERR_SET			3	// The message set allocated to the TIM
#define	THRERR_SET			4	// The message set allocated to the THR

// STR:

#define	STRERR_ASSERT		ErrNum(STRERR_SET, 1)	// At {1}:{2}, assertion failed: `{3}`
#define	STRERR_TRAILING_TEXT		ErrNum(STRERR_SET, 2)	// The number `{1}` in radix {2} ended at character {3}, leaving `{4}` unread
#define	STRERR_NO_DIGITS		ErrNum(STRERR_SET, 3)	// Failed to read a number from `{1}` in radix {2}
#define	STRERR_NUMBER_OVERFLOW		ErrNum(STRERR_SET, 4)	// The number `{1}` in radix {2} does not fit in `{3}`, overflowing at character {4}; the value returned is incomplete
#define	STRERR_NOT_NUMBER		ErrNum(STRERR_SET, 5)	// Cannot read `{1}` as a number in radix {2}: the character `{3}` at position {4} is not a digit
#define	STRERR_NEGATIVE_UNSIGNED		ErrNum(STRERR_SET, 7)	// Expected `{1}` to be unsigned in radix {2} but it is negative
#define	STRERR_ILLEGAL_RADIX		ErrNum(STRERR_SET, 6)	// Attempt to read `{1}` in illegal radix {2} was rejected
#define	STRERR_INDEX_OUT_OF_RANGE		ErrNum(STRERR_SET, 8)	// Indexing to {1} element {2} in array of {3} elements is not possible
// VAR:

#define	VARERR_WRONG_TYPE		ErrNum(VARERR_SET, 1)	// Expected `{1}`, not `{2}`
#define	VARERR_DOES_NOT_FIT		ErrNum(VARERR_SET, 2)	// Value {1} would overflow a `{2}`
#define	VARERR_NO_COERCION		ErrNum(VARERR_SET, 3)	// Conversion from `{1}` to `{2}` is not implemented, leaving it alone
// TIM:

#define	TIMERR_INVALID_YMDHMS		ErrNum(TIMERR_SET, 1)	// Date/Time {1}-{2}-{3} {4}:{5}:{6} does not exist
#define	TIMERR_INVALID_TEXT		ErrNum(TIMERR_SET, 2)	// `{1}` is not a valid time, a date or interval
#define	TIMERR_OUT_OF_RANGE		ErrNum(TIMERR_SET, 3)	// Date {1} falls outside the range we can hold (from {2} to {3})
#define	TIMERR_NO_DATE		ErrNum(TIMERR_SET, 4)	// Wanted a Date but only received a time of day
#define	TIMERR_NO_CLOCK		ErrNum(TIMERR_SET, 5)	// No clock is available to provide the current time
#define	TIMERR_NULL_VALUE		ErrNum(TIMERR_SET, 6)	// Null value `{1}` received for a {2}
#define	TIMERR_RESULT_OVERFLOW		ErrNum(TIMERR_SET, 7)	// Result of {1} would overflow a `{2}`
#define	TIMERR_NO_ZONE		ErrNum(TIMERR_SET, 8)	// You asked for localtime but we don't know the timezone. Using UTC
// THR:

#define	THRERR_CREATE_FAILED		ErrNum(THRERR_SET, 1)	// `{1}` returned {2} saying it failed to create a thread
#define	THRERR_STACK_REFUSED		ErrNum(THRERR_SET, 2)	// `{1}` refused a stack size of {2} bytes (error code {3}). Using the default size
#define	THRERR_JOIN_FAILED		ErrNum(THRERR_SET, 3)	// Failed to {1} for thread (error code {2}); its exit code is unknown
#define	THRERR_NO_CONDITION		ErrNum(THRERR_SET, 4)	// Cannot {1} condition variable because it was not successfully created
#define	THRERR_WAIT_FAILED		ErrNum(THRERR_SET, 5)	// Thread {1} failed (error code {2})
#define	THRERR_DELAY_FAILED		ErrNum(THRERR_SET, 6)	// Thread {1} failed (error code {2})

#endif	// STRPP_ERR_H
